### ISSUE TITLE
support parametric conf file

### ISSUE THREAD

**Issue by ujibang** [SoftInstigate/restheart-security#1]
Add support of mustache parameters in uiam.yml like RESTHeart supports it in restheart.yml

Expected Behavior

When restheart admin uses mustache parameter in uiamy.yml, mustache is replaced by a value like it's done for restheart.yml (using environment variables for example)

Current Behavior

We could not use mustache parameter

Context

Our organisation prefers starting docker container with environment variable and without configuration file in file system.

Environment

n.a.

Steps to Reproduce

n.a.

Possible Implementation

Use same algorithm as used for restheart.yml

**Comment by mkjsix** [comment]
We have updated the roadmap https://restheart.org/docs/roadmap/#restheart-platform-41

Expected Release Date End of September / Early October

**Comment by mkjsix** [comment]
This has been fixed in release https://github.com/SoftInstigate/restheart-security/releases/tag/1.1.0
