### ISSUE TITLE
upload artifact on maven central repo

### ISSUE THREAD

**Issue by ujibang** [SoftInstigate/restheart-security#2]
## Expected Behavior

travis build process should publish the jar on maven central repo

## Current Behavior

the jar is published on a private aws s3 repo

**Comment by christiangroth** [comment]
Do you have any plans to fix this soon? As we are currently trying to upgrade to RH 4.0 and we want do implement a Security Plugin we need this dependency. Thx!

**Comment by mkjsix** [comment]
Hi @christiangroth 
This has been in our TODO list for ages... However note that you can already get the Maven artifacts from Jitpack, see https://jitpack.io/#SoftInstigate/restheart-security/

Let me know if this is a viable solution for you.

**Comment by christiangroth** [comment]
Hi @mkjsix,

thanks for the quick reply! Yes that's a viable solution for starting the development and first tests of the update. Do you plan to push it to maven central soon or is this that long on your wishlist that it maybe will never get implemented?

**Comment by mkjsix** [comment]
@christiangroth honestly at the moment we are also using Jitpack as publishing on Maven is a multi-step process which is rather time consuming. It's probably something we'll delegate to a new intern in the following weeks, but I can't provide an ETA right now.

I'm closing this, feel free to re-open in case of further questions.

**Comment by ujibang** [comment]
Hi @christiangroth, I also suggest you to give this doc page a look https://restheart.org/docs/develop/packaging/

It suggests to install restheart-platform-core.jar as a local Maven dependency, so that you can package your plugin to RESTHeart Platform (not the OSS edition).
